### ISSUE TITLE
Deprecated XPCShowView

### ISSUE THREAD

**Issue by dougmcnerd** [dasdom/UIStackViewPlayground#1]
It appears the the following syntax is deprecated in iOS 9.1

Old (deprecated)
XCPShowView("hostView", view: hostView)

New (replacement)
XCPlaygroundPage.currentPage.liveView = hostView

**Comment by dasdom** [comment]
Fixed. Thank you!

**Comment by trevor-sonic** [comment]
```
 // Swift 3 
 import PlaygroundSupport
 PlaygroundPage.current.liveView = hostView
```

A full example with UIButton check http://lab.dejaworks.com/ios-swift-3-playground-uibutton-action/
